-- Esquema bàsic per Organització Casa
CREATE TABLE IF NOT EXISTS members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  base_points INT NOT NULL DEFAULT 10,
  icon VARCHAR(10) NULL
);

CREATE TABLE IF NOT EXISTS entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  member_id INT NOT NULL,
  task_id INT NOT NULL,
  date_iso DATETIME NOT NULL,
  quality TINYINT NOT NULL DEFAULT 3,
  notes TEXT,
  FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);
